### ISSUE TITLE
Adafruit I2C connection have a conflict on RPi.GPIO mode set

### ISSUE THREAD

**Issue by roxanaluca** [adafruit/Adafruit_Python_Extended_Bus#2]
Hi,

I have connected PCA9685 and Arducam Multi Camera Adapter on Raspberry Pi 3B+. I am using bus 3 for the PCA9685 connection and I have GPIO 26 for SCL and GPIO 16 for SDA. The problem is that when I put Arducam Multi-Camera adapter and the I2C Adafruit together there is a issue regarding on the following line
`gp.setmode(gp.BOARD)`
ValueError: A different mode has already been set
Could you tell me please how to solve this error?

I look forward to your reply.
Many thanks,

**Comment by makermelissa** [comment]
Could you please provide the entire error message with line numbers? I'm not seeing `gp.setmode(gp.BOARD)` in the source code for this library.

**Comment by roxanaluca** [comment]
Traceback (most recent call last):
  File "main.py", line 186, in <module>
    gp.setmode(gp.BOARD)
ValueError: A different mode has already been set!
```
import RPi.GPIO as gp
from adafruit_extended_bus import ExtendedI2C as I2C
from adafruit_servokit import ServoKit
class MotorDriver():
    def __init__(self):
        i2c = I2C(3)
        kit = ServoKit(channels=16, i2c=i2c)
        if kit.servo[1].angle < 0 or kit.servo[1].angle > 180:
            kit.servo[1].angle = 30
if __name__=="__main__":
    gp.setwarnings(False)
    gp.setmode(gp.BOARD)
    gp.setup(7,gp.OUT)
    gp.setup(11,gp.OUT)
    gp.setup(12,gp.OUT)
```

**Comment by ladyada** [comment]
you probably cannot mix rpi.gpio with circuitpython

**Comment by makermelissa** [comment]
Yeah, mixing them isn't a good idea. Blinka makes use of RPi.GPIO under the hood for the Raspberry Pis and it's not liking the manual overriding.

**Comment by roxanaluca** [comment]
Ok.. but I had to set pin 7,11,12 to False and True. Could you tell me how can I use them?

**Comment by makermelissa** [comment]
Yes. You'll want to use digitalio for this. See https://learn.adafruit.com/circuitpython-digital-inputs-and-outputs/digital-outputs for more info.
